# Generated by ffi-gen. Please do not change this file by hand.

require 'ffi'

module CEF
  extend FFI::Library
  ffi_lib 'cef'
  
  def self.attach_function(name, *_)
    begin; super; rescue FFI::NotFoundError => e
      (class << self; self; end).class_eval { define_method(name) { |*_| raise e } }
    end
  end
  
  # (Not documented)
  # 
  # @method string_map_alloc()
  # @return [FFI::Pointer(StringMapT)] 
  # @scope class
  attach_function :string_map_alloc, :cef_string_map_alloc, [], :pointer
  
  # (Not documented)
  # 
  # @method string_map_size(map)
  # @param [FFI::Pointer(StringMapT)] map 
  # @return [Integer] 
  # @scope class
  attach_function :string_map_size, :cef_string_map_size, [:pointer], :int
  
  # (Not documented)
  # 
  # @method string_map_find(map, key, value)
  # @param [FFI::Pointer(StringMapT)] map 
  # @param [FFI::Pointer(*StringT)] key 
  # @param [FFI::Pointer(*StringT)] value 
  # @return [Integer] 
  # @scope class
  attach_function :string_map_find, :cef_string_map_find, [:pointer, :pointer, :pointer], :int
  
  # (Not documented)
  # 
  # @method string_map_key(map, index, key)
  # @param [FFI::Pointer(StringMapT)] map 
  # @param [Integer] index 
  # @param [FFI::Pointer(*StringT)] key 
  # @return [Integer] 
  # @scope class
  attach_function :string_map_key, :cef_string_map_key, [:pointer, :int, :pointer], :int
  
  # (Not documented)
  # 
  # @method string_map_value(map, index, value)
  # @param [FFI::Pointer(StringMapT)] map 
  # @param [Integer] index 
  # @param [FFI::Pointer(*StringT)] value 
  # @return [Integer] 
  # @scope class
  attach_function :string_map_value, :cef_string_map_value, [:pointer, :int, :pointer], :int
  
  # (Not documented)
  # 
  # @method string_map_append(map, key, value)
  # @param [FFI::Pointer(StringMapT)] map 
  # @param [FFI::Pointer(*StringT)] key 
  # @param [FFI::Pointer(*StringT)] value 
  # @return [Integer] 
  # @scope class
  attach_function :string_map_append, :cef_string_map_append, [:pointer, :pointer, :pointer], :int
  
  # (Not documented)
  # 
  # @method string_map_clear(map)
  # @param [FFI::Pointer(StringMapT)] map 
  # @return [nil] 
  # @scope class
  attach_function :string_map_clear, :cef_string_map_clear, [:pointer], :void
  
  # (Not documented)
  # 
  # @method string_map_free(map)
  # @param [FFI::Pointer(StringMapT)] map 
  # @return [nil] 
  # @scope class
  attach_function :string_map_free, :cef_string_map_free, [:pointer], :void
  
end
