# Generated by ffi-gen. Please do not change this file by hand.

require 'ffi'

module CEF
  extend FFI::Library
  ffi_lib 'cef'
  
  def self.attach_function(name, *_)
    begin; super; rescue FFI::NotFoundError => e
      (class << self; self; end).class_eval { define_method(name) { |*_| raise e } }
    end
  end
  
  # ///
  # 
  # <em>This entry is only for documentation and no real method. The FFI::Enum can be accessed via #enum_type(:log_severity_t).</em>
  # 
  # === Options:
  # :logseverity_verbose ::
  #   
  # :logseverity_info ::
  #   
  # :logseverity_warning ::
  #   
  # :logseverity_error ::
  #   
  # :logseverity_error_report ::
  #   
  # :logseverity_disable ::
  #   // Disables logging completely.
  # 
  # @method _enum_log_severity_t_
  # @return [Symbol]
  # @scope class
  enum :log_severity_t, [
    :logseverity_verbose, -1,
    :logseverity_info, 0,
    :logseverity_warning, 1,
    :logseverity_error, 2,
    :logseverity_error_report, 3,
    :logseverity_disable, 99
  ]
  
  # ///
  # 
  # = Fields:
  # :size ::
  #   (Integer) ///
  # :single_process ::
  #   (Integer) ///
  # :browser_subprocess_path ::
  #   (unknown) ///
  # :multi_threaded_message_loop ::
  #   (Integer) ///
  # :command_line_args_disabled ::
  #   (Integer) ///
  # :cache_path ::
  #   (unknown) ///
  # :user_agent ::
  #   (unknown) ///
  # :product_version ::
  #   (unknown) ///
  # :locale ::
  #   (unknown) ///
  # :log_file ::
  #   (unknown) ///
  # :log_severity ::
  #   (Symbol from _enum_log_severity_t_) ///
  # :javascript_flags ::
  #   (unknown) ///
  # :auto_detect_proxy_settings_enabled ::
  #   (Integer) ///
  # :pack_file_path ::
  #   (unknown) ///
  # :locales_dir_path ::
  #   (unknown) ///
  # :pack_loading_disabled ::
  #   (Integer) ///
  # :remote_debugging_port ::
  #   (Integer) ///
  class CefSettingsT < FFI::Struct
    layout :size, :ulong,
           :single_process, :int,
           :browser_subprocess_path, :char,
           :multi_threaded_message_loop, :int,
           :command_line_args_disabled, :int,
           :cache_path, :char,
           :user_agent, :char,
           :product_version, :char,
           :locale, :char,
           :log_file, :char,
           :log_severity, :log_severity_t,
           :javascript_flags, :char,
           :auto_detect_proxy_settings_enabled, :int,
           :pack_file_path, :char,
           :locales_dir_path, :char,
           :pack_loading_disabled, :int,
           :remote_debugging_port, :int
  end
  
  # ///
  # 
  # = Fields:
  # :size ::
  #   (Integer) ///
  # :standard_font_family ::
  #   (unknown) ///
  # :fixed_font_family ::
  #   (unknown) 
  # :serif_font_family ::
  #   (unknown) 
  # :sans_serif_font_family ::
  #   (unknown) 
  # :cursive_font_family ::
  #   (unknown) 
  # :fantasy_font_family ::
  #   (unknown) 
  # :default_font_size ::
  #   (Integer) 
  # :default_fixed_font_size ::
  #   (Integer) 
  # :minimum_font_size ::
  #   (Integer) 
  # :minimum_logical_font_size ::
  #   (Integer) 
  # :remote_fonts_disabled ::
  #   (Integer) ///
  # :default_encoding ::
  #   (unknown) ///
  # :encoding_detector_enabled ::
  #   (Integer) ///
  # :javascript_disabled ::
  #   (Integer) ///
  # :javascript_open_windows_disallowed ::
  #   (Integer) ///
  # :javascript_close_windows_disallowed ::
  #   (Integer) ///
  # :javascript_access_clipboard_disallowed ::
  #   (Integer) ///
  # :dom_paste_disabled ::
  #   (Integer) ///
  # :caret_browsing_enabled ::
  #   (Integer) ///
  # :java_disabled ::
  #   (Integer) ///
  # :plugins_disabled ::
  #   (Integer) ///
  # :universal_access_from_file_urls_allowed ::
  #   (Integer) ///
  # :file_access_from_file_urls_allowed ::
  #   (Integer) ///
  # :web_security_disabled ::
  #   (Integer) ///
  # :xss_auditor_enabled ::
  #   (Integer) ///
  # :image_load_disabled ::
  #   (Integer) ///
  # :shrink_standalone_images_to_fit ::
  #   (Integer) ///
  # :site_specific_quirks_disabled ::
  #   (Integer) ///
  # :text_area_resize_disabled ::
  #   (Integer) ///
  # :page_cache_disabled ::
  #   (Integer) ///
  # :tab_to_links_disabled ::
  #   (Integer) ///
  # :hyperlink_auditing_disabled ::
  #   (Integer) ///
  # :user_style_sheet_enabled ::
  #   (Integer) ///
  # :user_style_sheet_location ::
  #   (unknown) ///
  # :author_and_user_styles_disabled ::
  #   (Integer) ///
  # :local_storage_disabled ::
  #   (Integer) ///
  # :databases_disabled ::
  #   (Integer) ///
  # :application_cache_disabled ::
  #   (Integer) ///
  # :webgl_disabled ::
  #   (Integer) ///
  # :accelerated_compositing_disabled ::
  #   (Integer) ///
  # :accelerated_layers_disabled ::
  #   (Integer) ///
  # :accelerated_video_disabled ::
  #   (Integer) ///
  # :accelerated_2d_canvas_disabled ::
  #   (Integer) ///
  # :accelerated_painting_enabled ::
  #   (Integer) ///
  # :accelerated_filters_enabled ::
  #   (Integer) ///
  # :accelerated_plugins_disabled ::
  #   (Integer) ///
  # :developer_tools_disabled ::
  #   (Integer) ///
  # :fullscreen_enabled ::
  #   (Integer) ///
  class CefBrowserSettingsT < FFI::Struct
    layout :size, :ulong,
           :standard_font_family, :char,
           :fixed_font_family, :char,
           :serif_font_family, :char,
           :sans_serif_font_family, :char,
           :cursive_font_family, :char,
           :fantasy_font_family, :char,
           :default_font_size, :int,
           :default_fixed_font_size, :int,
           :minimum_font_size, :int,
           :minimum_logical_font_size, :int,
           :remote_fonts_disabled, :int,
           :default_encoding, :char,
           :encoding_detector_enabled, :int,
           :javascript_disabled, :int,
           :javascript_open_windows_disallowed, :int,
           :javascript_close_windows_disallowed, :int,
           :javascript_access_clipboard_disallowed, :int,
           :dom_paste_disabled, :int,
           :caret_browsing_enabled, :int,
           :java_disabled, :int,
           :plugins_disabled, :int,
           :universal_access_from_file_urls_allowed, :int,
           :file_access_from_file_urls_allowed, :int,
           :web_security_disabled, :int,
           :xss_auditor_enabled, :int,
           :image_load_disabled, :int,
           :shrink_standalone_images_to_fit, :int,
           :site_specific_quirks_disabled, :int,
           :text_area_resize_disabled, :int,
           :page_cache_disabled, :int,
           :tab_to_links_disabled, :int,
           :hyperlink_auditing_disabled, :int,
           :user_style_sheet_enabled, :int,
           :user_style_sheet_location, :char,
           :author_and_user_styles_disabled, :int,
           :local_storage_disabled, :int,
           :databases_disabled, :int,
           :application_cache_disabled, :int,
           :webgl_disabled, :int,
           :accelerated_compositing_disabled, :int,
           :accelerated_layers_disabled, :int,
           :accelerated_video_disabled, :int,
           :accelerated_2d_canvas_disabled, :int,
           :accelerated_painting_enabled, :int,
           :accelerated_filters_enabled, :int,
           :accelerated_plugins_disabled, :int,
           :developer_tools_disabled, :int,
           :fullscreen_enabled, :int
  end
  
  # ///
  # 
  # = Fields:
  # :spec ::
  #   (unknown) ///
  # :scheme ::
  #   (unknown) ///
  # :username ::
  #   (unknown) ///
  # :password ::
  #   (unknown) ///
  # :host ::
  #   (unknown) ///
  # :port ::
  #   (unknown) ///
  # :path ::
  #   (unknown) ///
  # :query ::
  #   (unknown) ///
  class CefUrlpartsT < FFI::Struct
    layout :spec, :char,
           :scheme, :char,
           :username, :char,
           :password, :char,
           :host, :char,
           :port, :char,
           :path, :char,
           :query, :char
  end
  
  # ///
  # 
  # = Fields:
  # :name ::
  #   (unknown) ///
  # :value ::
  #   (unknown) ///
  # :domain ::
  #   (unknown) ///
  # :path ::
  #   (unknown) ///
  # :secure ::
  #   (Integer) ///
  # :httponly ::
  #   (Integer) ///
  # :creation ::
  #   (unknown) ///
  # :last_access ::
  #   (unknown) ///
  # :has_expires ::
  #   (Integer) ///
  # :expires ::
  #   (unknown) 
  class CefCookieT < FFI::Struct
    layout :name, :char,
           :value, :char,
           :domain, :char,
           :path, :char,
           :secure, :int,
           :httponly, :int,
           :creation, :char,
           :last_access, :char,
           :has_expires, :int,
           :expires, :char
  end
  
  # ///
  # 
  # <em>This entry is only for documentation and no real method. The FFI::Enum can be accessed via #enum_type(:storage_type_t).</em>
  # 
  # === Options:
  # :st_localstorage ::
  #   
  # :st_sessionstorage ::
  #   
  # 
  # @method _enum_storage_type_t_
  # @return [Symbol]
  # @scope class
  enum :storage_type_t, [
    :st_localstorage, 0,
    :st_sessionstorage, 1
  ]
  
  # ///
  # 
  # <em>This entry is only for documentation and no real method. The FFI::Enum can be accessed via #enum_type(:errorcode_t).</em>
  # 
  # === Options:
  # :err_none ::
  #   
  # :err_failed ::
  #   
  # :err_aborted ::
  #   
  # :err_invalid_argument ::
  #   
  # :err_invalid_handle ::
  #   
  # :err_file_not_found ::
  #   
  # :err_timed_out ::
  #   
  # :err_file_too_big ::
  #   
  # :err_unexpected ::
  #   
  # :err_access_denied ::
  #   
  # :err_not_implemented ::
  #   
  # :err_connection_closed ::
  #   
  # :err_connection_reset ::
  #   
  # :err_connection_refused ::
  #   
  # :err_connection_aborted ::
  #   
  # :err_connection_failed ::
  #   
  # :err_name_not_resolved ::
  #   
  # :err_internet_disconnected ::
  #   
  # :err_ssl_protocol_error ::
  #   
  # :err_address_invalid ::
  #   
  # :err_address_unreachable ::
  #   
  # :err_ssl_client_auth_cert_needed ::
  #   
  # :err_tunnel_connection_failed ::
  #   
  # :err_no_ssl_versions_enabled ::
  #   
  # :err_ssl_version_or_cipher_mismatch ::
  #   
  # :err_ssl_renegotiation_requested ::
  #   
  # :err_cert_common_name_invalid ::
  #   
  # :err_cert_date_invalid ::
  #   
  # :err_cert_authority_invalid ::
  #   
  # :err_cert_contains_errors ::
  #   
  # :err_cert_no_revocation_mechanism ::
  #   
  # :err_cert_unable_to_check_revocation ::
  #   
  # :err_cert_revoked ::
  #   
  # :err_cert_invalid ::
  #   
  # :err_cert_end ::
  #   
  # :err_invalid_url ::
  #   
  # :err_disallowed_url_scheme ::
  #   
  # :err_unknown_url_scheme ::
  #   
  # :err_too_many_redirects ::
  #   
  # :err_unsafe_redirect ::
  #   
  # :err_unsafe_port ::
  #   
  # :err_invalid_response ::
  #   
  # :err_invalid_chunked_encoding ::
  #   
  # :err_method_not_supported ::
  #   
  # :err_unexpected_proxy_auth ::
  #   
  # :err_empty_response ::
  #   
  # :err_response_headers_too_big ::
  #   
  # :err_cache_miss ::
  #   
  # :err_insecure_response ::
  #   
  # 
  # @method _enum_errorcode_t_
  # @return [Symbol]
  # @scope class
  enum :errorcode_t, [
    :err_none, 0,
    :err_failed, -2,
    :err_aborted, -3,
    :err_invalid_argument, -4,
    :err_invalid_handle, -5,
    :err_file_not_found, -6,
    :err_timed_out, -7,
    :err_file_too_big, -8,
    :err_unexpected, -9,
    :err_access_denied, -10,
    :err_not_implemented, -11,
    :err_connection_closed, -100,
    :err_connection_reset, -101,
    :err_connection_refused, -102,
    :err_connection_aborted, -103,
    :err_connection_failed, -104,
    :err_name_not_resolved, -105,
    :err_internet_disconnected, -106,
    :err_ssl_protocol_error, -107,
    :err_address_invalid, -108,
    :err_address_unreachable, -109,
    :err_ssl_client_auth_cert_needed, -110,
    :err_tunnel_connection_failed, -111,
    :err_no_ssl_versions_enabled, -112,
    :err_ssl_version_or_cipher_mismatch, -113,
    :err_ssl_renegotiation_requested, -114,
    :err_cert_common_name_invalid, -200,
    :err_cert_date_invalid, -201,
    :err_cert_authority_invalid, -202,
    :err_cert_contains_errors, -203,
    :err_cert_no_revocation_mechanism, -204,
    :err_cert_unable_to_check_revocation, -205,
    :err_cert_revoked, -206,
    :err_cert_invalid, -207,
    :err_cert_end, -208,
    :err_invalid_url, -300,
    :err_disallowed_url_scheme, -301,
    :err_unknown_url_scheme, -302,
    :err_too_many_redirects, -310,
    :err_unsafe_redirect, -311,
    :err_unsafe_port, -312,
    :err_invalid_response, -320,
    :err_invalid_chunked_encoding, -321,
    :err_method_not_supported, -322,
    :err_unexpected_proxy_auth, -323,
    :err_empty_response, -324,
    :err_response_headers_too_big, -325,
    :err_cache_miss, -400,
    :err_insecure_response, -501
  ]
  
  # ///
  # 
  # <em>This entry is only for documentation and no real method. The FFI::Enum can be accessed via #enum_type(:v8_accesscontrol_t).</em>
  # 
  # === Options:
  # :access_control_default ::
  #   
  # :access_control_all_can_read ::
  #   
  # :access_control_all_can_write ::
  #   
  # :access_control_prohibits_overwriting ::
  #   
  # 
  # @method _enum_v8_accesscontrol_t_
  # @return [Symbol]
  # @scope class
  enum :v8_accesscontrol_t, [
    :access_control_default, 0,
    :access_control_all_can_read, 1,
    :access_control_all_can_write, 2,
    :access_control_prohibits_overwriting, 4
  ]
  
  # ///
  # 
  # <em>This entry is only for documentation and no real method. The FFI::Enum can be accessed via #enum_type(:v8_propertyattribute_t).</em>
  # 
  # === Options:
  # :property_attribute_none ::
  #   
  # :property_attribute_readonly ::
  #   //   Configurable
  # :property_attribute_dontenum ::
  #   // Not writeable
  # :property_attribute_dontdelete ::
  #   // Not enumerable
  # 
  # @method _enum_v8_propertyattribute_t_
  # @return [Symbol]
  # @scope class
  enum :v8_propertyattribute_t, [
    :property_attribute_none, 0,
    :property_attribute_readonly, 1,
    :property_attribute_dontenum, 2,
    :property_attribute_dontdelete, 4
  ]
  
  # ///
  # 
  # <em>This entry is only for documentation and no real method. The FFI::Enum can be accessed via #enum_type(:postdataelement_type_t).</em>
  # 
  # === Options:
  # :pde_type_empty ::
  #   
  # :pde_type_bytes ::
  #   
  # :pde_type_file ::
  #   
  # 
  # @method _enum_postdataelement_type_t_
  # @return [Symbol]
  # @scope class
  enum :postdataelement_type_t, [
    :pde_type_empty, 0,
    :pde_type_bytes, 1,
    :pde_type_file, 2
  ]
  
  # ///
  # 
  # <em>This entry is only for documentation and no real method. The FFI::Enum can be accessed via #enum_type(:urlrequest_flags_t).</em>
  # 
  # === Options:
  # :ur_flag_none ::
  #   ///
  # :ur_flag_skip_cache ::
  #   ///
  # :ur_flag_allow_cached_credentials ::
  #   ///
  # :ur_flag_allow_cookies ::
  #   ///
  # :ur_flag_report_upload_progress ::
  #   ///
  # :ur_flag_report_load_timing ::
  #   ///
  # :ur_flag_report_raw_headers ::
  #   ///
  # :ur_flag_no_download_data ::
  #   ///
  # :ur_flag_no_retry_on_5xx ::
  #   ///
  # 
  # @method _enum_urlrequest_flags_t_
  # @return [Symbol]
  # @scope class
  enum :urlrequest_flags_t, [
    :ur_flag_none, 0,
    :ur_flag_skip_cache, 1,
    :ur_flag_allow_cached_credentials, 2,
    :ur_flag_allow_cookies, 4,
    :ur_flag_report_upload_progress, 8,
    :ur_flag_report_load_timing, 16,
    :ur_flag_report_raw_headers, 32,
    :ur_flag_no_download_data, 64,
    :ur_flag_no_retry_on_5xx, 128
  ]
  
  # ///
  # 
  # <em>This entry is only for documentation and no real method. The FFI::Enum can be accessed via #enum_type(:urlrequest_status_t).</em>
  # 
  # === Options:
  # :ur_unknown ::
  #   ///
  # :ur_success ::
  #   ///
  # :ur_io_pending ::
  #   ///
  # :ur_handled_externally ::
  #   ///
  # :ur_canceled ::
  #   ///
  # :ur_failed ::
  #   ///
  # 
  # @method _enum_urlrequest_status_t_
  # @return [Symbol]
  # @scope class
  enum :urlrequest_status_t, [
    :ur_unknown, 0,
    :ur_success, 1,
    :ur_io_pending, 2,
    :ur_handled_externally, 3,
    :ur_canceled, 4,
    :ur_failed, 5
  ]
  
  # ///
  # 
  # = Fields:
  # :x ::
  #   (Integer) 
  # :y ::
  #   (Integer) 
  # :width ::
  #   (Integer) 
  # :height ::
  #   (Integer) 
  class CefRectT < FFI::Struct
    layout :x, :int,
           :y, :int,
           :width, :int,
           :height, :int
  end
  
  # ///
  # 
  # <em>This entry is only for documentation and no real method. The FFI::Enum can be accessed via #enum_type(:process_id_t).</em>
  # 
  # === Options:
  # :pid_browser ::
  #   ///
  # :pid_renderer ::
  #   ///
  # 
  # @method _enum_process_id_t_
  # @return [Symbol]
  # @scope class
  enum :process_id_t, [
    :pid_browser, 0,
    :pid_renderer, 1
  ]
  
  # ///
  # 
  # <em>This entry is only for documentation and no real method. The FFI::Enum can be accessed via #enum_type(:thread_id_t).</em>
  # 
  # === Options:
  # :tid_ui ::
  #   ///
  # :tid_db ::
  #   ///
  # :tid_file ::
  #   ///
  # :tid_file_user_blocking ::
  #   ///
  # :tid_process_launcher ::
  #   ///
  # :tid_cache ::
  #   ///
  # :tid_io ::
  #   ///
  # :tid_renderer ::
  #   ///
  # 
  # @method _enum_thread_id_t_
  # @return [Symbol]
  # @scope class
  enum :thread_id_t, [
    :tid_ui, 0,
    :tid_db, 1,
    :tid_file, 2,
    :tid_file_user_blocking, 3,
    :tid_process_launcher, 4,
    :tid_cache, 5,
    :tid_io, 6,
    :tid_renderer, 7
  ]
  
  # ///
  # 
  # <em>This entry is only for documentation and no real method. The FFI::Enum can be accessed via #enum_type(:value_type_t).</em>
  # 
  # === Options:
  # :vtype_invalid ::
  #   
  # :vtype_null ::
  #   
  # :vtype_bool ::
  #   
  # :vtype_int ::
  #   
  # :vtype_double ::
  #   
  # :vtype_string ::
  #   
  # :vtype_binary ::
  #   
  # :vtype_dictionary ::
  #   
  # :vtype_list ::
  #   
  # 
  # @method _enum_value_type_t_
  # @return [Symbol]
  # @scope class
  enum :value_type_t, [
    :vtype_invalid, 0,
    :vtype_null, 1,
    :vtype_bool, 2,
    :vtype_int, 3,
    :vtype_double, 4,
    :vtype_string, 5,
    :vtype_binary, 6,
    :vtype_dictionary, 7,
    :vtype_list, 8
  ]
  
  # ///
  # 
  # <em>This entry is only for documentation and no real method. The FFI::Enum can be accessed via #enum_type(:jsdialog_type_t).</em>
  # 
  # === Options:
  # :jsdialogtype_alert ::
  #   
  # :jsdialogtype_confirm ::
  #   
  # :jsdialogtype_prompt ::
  #   
  # 
  # @method _enum_jsdialog_type_t_
  # @return [Symbol]
  # @scope class
  enum :jsdialog_type_t, [
    :jsdialogtype_alert, 0,
    :jsdialogtype_confirm, 1,
    :jsdialogtype_prompt, 2
  ]
  
  # ///
  # 
  # <em>This entry is only for documentation and no real method. The FFI::Enum can be accessed via #enum_type(:menu_id_t).</em>
  # 
  # === Options:
  # :back ::
  #   // Navigation.
  # :forward ::
  #   
  # :reload ::
  #   
  # :reload_nocache ::
  #   
  # :stopload ::
  #   
  # :undo ::
  #   // Editing.
  # :redo_ ::
  #   
  # :cut ::
  #   
  # :copy ::
  #   
  # :paste ::
  #   
  # :delete ::
  #   
  # :select_all ::
  #   
  # :find ::
  #   // Miscellaneous.
  # :print ::
  #   
  # :view_source ::
  #   
  # :user_first ::
  #   // defined in the tools/gritsettings/resource_ids file.
  # :user_last ::
  #   
  # 
  # @method _enum_menu_id_t_
  # @return [Symbol]
  # @scope class
  enum :menu_id_t, [
    :back, 100,
    :forward, 101,
    :reload, 102,
    :reload_nocache, 103,
    :stopload, 104,
    :undo, 110,
    :redo_, 111,
    :cut, 112,
    :copy, 113,
    :paste, 114,
    :delete, 115,
    :select_all, 116,
    :find, 130,
    :print, 131,
    :view_source, 132,
    :user_first, 26500,
    :user_last, 28500
  ]
  
  # ///
  # 
  # <em>This entry is only for documentation and no real method. The FFI::Enum can be accessed via #enum_type(:event_flags_t).</em>
  # 
  # === Options:
  # :eventflag_none ::
  #   
  # :eventflag_caps_lock_down ::
  #   
  # :eventflag_shift_down ::
  #   
  # :eventflag_control_down ::
  #   
  # :eventflag_alt_down ::
  #   
  # :eventflag_left_mouse_button ::
  #   
  # :eventflag_middle_mouse_button ::
  #   
  # :eventflag_right_mouse_button ::
  #   
  # :eventflag_command_down ::
  #   // Mac OS-X command key.
  # :eventflag_extended ::
  #   // Windows extended key (see WM_KEYDOWN doc).
  # 
  # @method _enum_event_flags_t_
  # @return [Symbol]
  # @scope class
  enum :event_flags_t, [
    :eventflag_none, 0,
    :eventflag_caps_lock_down, 1,
    :eventflag_shift_down, 2,
    :eventflag_control_down, 4,
    :eventflag_alt_down, 8,
    :eventflag_left_mouse_button, 16,
    :eventflag_middle_mouse_button, 32,
    :eventflag_right_mouse_button, 64,
    :eventflag_command_down, 128,
    :eventflag_extended, 256
  ]
  
  # ///
  # 
  # <em>This entry is only for documentation and no real method. The FFI::Enum can be accessed via #enum_type(:menu_item_type_t).</em>
  # 
  # === Options:
  # :menuitemtype_none ::
  #   
  # :menuitemtype_command ::
  #   
  # :menuitemtype_check ::
  #   
  # :menuitemtype_radio ::
  #   
  # :menuitemtype_separator ::
  #   
  # :menuitemtype_submenu ::
  #   
  # 
  # @method _enum_menu_item_type_t_
  # @return [Symbol]
  # @scope class
  enum :menu_item_type_t, [
    :menuitemtype_none, 0,
    :menuitemtype_command, 1,
    :menuitemtype_check, 2,
    :menuitemtype_radio, 3,
    :menuitemtype_separator, 4,
    :menuitemtype_submenu, 5
  ]
  
  # ///
  # 
  # <em>This entry is only for documentation and no real method. The FFI::Enum can be accessed via #enum_type(:context_menu_type_flags_t).</em>
  # 
  # === Options:
  # :cm_typeflag_none ::
  #   ///
  # :cm_typeflag_page ::
  #   ///
  # :cm_typeflag_frame ::
  #   ///
  # :cm_typeflag_link ::
  #   ///
  # :cm_typeflag_media ::
  #   ///
  # :cm_typeflag_selection ::
  #   ///
  # :cm_typeflag_editable ::
  #   ///
  # 
  # @method _enum_context_menu_type_flags_t_
  # @return [Symbol]
  # @scope class
  enum :context_menu_type_flags_t, [
    :cm_typeflag_none, 0,
    :cm_typeflag_page, 1,
    :cm_typeflag_frame, 2,
    :cm_typeflag_link, 4,
    :cm_typeflag_media, 8,
    :cm_typeflag_selection, 16,
    :cm_typeflag_editable, 32
  ]
  
  # ///
  # 
  # <em>This entry is only for documentation and no real method. The FFI::Enum can be accessed via #enum_type(:context_menu_media_type_t).</em>
  # 
  # === Options:
  # :cm_mediatype_none ::
  #   ///
  # :cm_mediatype_image ::
  #   ///
  # :cm_mediatype_video ::
  #   ///
  # :cm_mediatype_audio ::
  #   ///
  # :cm_mediatype_file ::
  #   ///
  # :cm_mediatype_plugin ::
  #   ///
  # 
  # @method _enum_context_menu_media_type_t_
  # @return [Symbol]
  # @scope class
  enum :context_menu_media_type_t, [
    :cm_mediatype_none, 0,
    :cm_mediatype_image, 1,
    :cm_mediatype_video, 2,
    :cm_mediatype_audio, 3,
    :cm_mediatype_file, 4,
    :cm_mediatype_plugin, 5
  ]
  
  # ///
  # 
  # <em>This entry is only for documentation and no real method. The FFI::Enum can be accessed via #enum_type(:context_menu_media_state_flags_t).</em>
  # 
  # === Options:
  # :cm_mediaflag_none ::
  #   
  # :cm_mediaflag_error ::
  #   
  # :cm_mediaflag_paused ::
  #   
  # :cm_mediaflag_muted ::
  #   
  # :cm_mediaflag_loop ::
  #   
  # :cm_mediaflag_can_save ::
  #   
  # :cm_mediaflag_has_audio ::
  #   
  # :cm_mediaflag_has_video ::
  #   
  # :cm_mediaflag_control_root_element ::
  #   
  # :cm_mediaflag_can_print ::
  #   
  # :cm_mediaflag_can_rotate ::
  #   
  # 
  # @method _enum_context_menu_media_state_flags_t_
  # @return [Symbol]
  # @scope class
  enum :context_menu_media_state_flags_t, [
    :cm_mediaflag_none, 0,
    :cm_mediaflag_error, 1,
    :cm_mediaflag_paused, 2,
    :cm_mediaflag_muted, 4,
    :cm_mediaflag_loop, 8,
    :cm_mediaflag_can_save, 16,
    :cm_mediaflag_has_audio, 32,
    :cm_mediaflag_has_video, 64,
    :cm_mediaflag_control_root_element, 128,
    :cm_mediaflag_can_print, 256,
    :cm_mediaflag_can_rotate, 512
  ]
  
  # ///
  # 
  # <em>This entry is only for documentation and no real method. The FFI::Enum can be accessed via #enum_type(:context_menu_edit_state_flags_t).</em>
  # 
  # === Options:
  # :cm_editflag_none ::
  #   
  # :cm_editflag_can_undo ::
  #   
  # :cm_editflag_can_redo ::
  #   
  # :cm_editflag_can_cut ::
  #   
  # :cm_editflag_can_copy ::
  #   
  # :cm_editflag_can_paste ::
  #   
  # :cm_editflag_can_delete ::
  #   
  # :cm_editflag_can_select_all ::
  #   
  # :cm_editflag_can_translate ::
  #   
  # 
  # @method _enum_context_menu_edit_state_flags_t_
  # @return [Symbol]
  # @scope class
  enum :context_menu_edit_state_flags_t, [
    :cm_editflag_none, 0,
    :cm_editflag_can_undo, 1,
    :cm_editflag_can_redo, 2,
    :cm_editflag_can_cut, 4,
    :cm_editflag_can_copy, 8,
    :cm_editflag_can_paste, 16,
    :cm_editflag_can_delete, 32,
    :cm_editflag_can_select_all, 64,
    :cm_editflag_can_translate, 128
  ]
  
  # ///
  # 
  # <em>This entry is only for documentation and no real method. The FFI::Enum can be accessed via #enum_type(:key_event_type_t).</em>
  # 
  # === Options:
  # :keyevent_rawkeydown ::
  #   
  # :keyevent_keydown ::
  #   
  # :keyevent_keyup ::
  #   
  # :keyevent_char ::
  #   
  # 
  # @method _enum_key_event_type_t_
  # @return [Symbol]
  # @scope class
  enum :key_event_type_t, [
    :keyevent_rawkeydown, 0,
    :keyevent_keydown, 1,
    :keyevent_keyup, 2,
    :keyevent_char, 3
  ]
  
  # ///
  # 
  # <em>This entry is only for documentation and no real method. The FFI::Enum can be accessed via #enum_type(:key_event_modifiers_t).</em>
  # 
  # === Options:
  # :shift ::
  #   
  # :ctrl ::
  #   
  # :alt ::
  #   
  # :meta ::
  #   
  # :keypad ::
  #   
  # 
  # @method _enum_key_event_modifiers_t_
  # @return [Symbol]
  # @scope class
  enum :key_event_modifiers_t, [
    :shift, 1,
    :ctrl, 2,
    :alt, 4,
    :meta, 8,
    :keypad, 16
  ]
  
  # ///
  # 
  # = Fields:
  # :type ::
  #   (Symbol from _enum_key_event_type_t_) ///
  # :modifiers ::
  #   (Integer) ///
  # :windows_key_code ::
  #   (Integer) ///
  # :native_key_code ::
  #   (Integer) ///
  # :is_system_key ::
  #   (Integer) ///
  # :character ::
  #   (Integer) ///
  # :unmodified_character ::
  #   (Integer) ///
  # :focus_on_editable_field ::
  #   (Integer) ///
  class CefKeyEventT < FFI::Struct
    layout :type, :key_event_type_t,
           :modifiers, :int,
           :windows_key_code, :int,
           :native_key_code, :int,
           :is_system_key, :int,
           :character, :ushort,
           :unmodified_character, :ushort,
           :focus_on_editable_field, :int
  end
  
  # ///
  # 
  # <em>This entry is only for documentation and no real method. The FFI::Enum can be accessed via #enum_type(:focus_source_t).</em>
  # 
  # === Options:
  # :navigation ::
  #   ///
  # :system ::
  #   ///
  # 
  # @method _enum_focus_source_t_
  # @return [Symbol]
  # @scope class
  enum :focus_source_t, [
    :navigation, 0,
    :system, 1
  ]
  
  # ///
  # 
  # <em>This entry is only for documentation and no real method. The FFI::Enum can be accessed via #enum_type(:xml_encoding_type_t).</em>
  # 
  # === Options:
  # :none ::
  #   
  # :utf8 ::
  #   
  # :utf16le ::
  #   
  # :utf16be ::
  #   
  # :ascii ::
  #   
  # 
  # @method _enum_xml_encoding_type_t_
  # @return [Symbol]
  # @scope class
  enum :xml_encoding_type_t, [
    :none, 0,
    :utf8, 1,
    :utf16le, 2,
    :utf16be, 3,
    :ascii, 4
  ]
  
  # ///
  # 
  # <em>This entry is only for documentation and no real method. The FFI::Enum can be accessed via #enum_type(:xml_node_type_t).</em>
  # 
  # === Options:
  # :unsupported ::
  #   
  # :processing_instruction ::
  #   
  # :document_type ::
  #   
  # :element_start ::
  #   
  # :element_end ::
  #   
  # :attribute ::
  #   
  # :text ::
  #   
  # :cdata ::
  #   
  # :entity_reference ::
  #   
  # :whitespace ::
  #   
  # :comment ::
  #   
  # 
  # @method _enum_xml_node_type_t_
  # @return [Symbol]
  # @scope class
  enum :xml_node_type_t, [
    :unsupported, 0,
    :processing_instruction, 1,
    :document_type, 2,
    :element_start, 3,
    :element_end, 4,
    :attribute, 5,
    :text, 6,
    :cdata, 7,
    :entity_reference, 8,
    :whitespace, 9,
    :comment, 10
  ]
  
  # ///
  # 
  # <em>This entry is only for documentation and no real method. The FFI::Enum can be accessed via #enum_type(:handler_statustype_t).</em>
  # 
  # === Options:
  # :text ::
  #   
  # :mouseover_url ::
  #   
  # :keyboard_focus_url ::
  #   
  # 
  # @method _enum_handler_statustype_t_
  # @return [Symbol]
  # @scope class
  enum :handler_statustype_t, [
    :text, 0,
    :mouseover_url, 1,
    :keyboard_focus_url, 2
  ]
  
  # ///
  # 
  # = Fields:
  # :x ::
  #   (Integer) 
  # :x_set ::
  #   (Integer) 
  # :y ::
  #   (Integer) 
  # :y_set ::
  #   (Integer) 
  # :width ::
  #   (Integer) 
  # :width_set ::
  #   (Integer) 
  # :height ::
  #   (Integer) 
  # :height_set ::
  #   (Integer) 
  # :menu_bar_visible ::
  #   (Integer) 
  # :status_bar_visible ::
  #   (Integer) 
  # :tool_bar_visible ::
  #   (Integer) 
  # :location_bar_visible ::
  #   (Integer) 
  # :scrollbars_visible ::
  #   (Integer) 
  # :resizable ::
  #   (Integer) 
  # :fullscreen ::
  #   (Integer) 
  # :dialog ::
  #   (Integer) 
  # :additional_features ::
  #   (FFI::Pointer(StringListT)) 
  class CefPopupFeaturesT < FFI::Struct
    layout :x, :int,
           :x_set, :int,
           :y, :int,
           :y_set, :int,
           :width, :int,
           :width_set, :int,
           :height, :int,
           :height_set, :int,
           :menu_bar_visible, :int,
           :status_bar_visible, :int,
           :tool_bar_visible, :int,
           :location_bar_visible, :int,
           :scrollbars_visible, :int,
           :resizable, :int,
           :fullscreen, :int,
           :dialog, :int,
           :additional_features, :pointer
  end
  
  # ///
  # 
  # <em>This entry is only for documentation and no real method. The FFI::Enum can be accessed via #enum_type(:proxy_type_t).</em>
  # 
  # === Options:
  # :direct ::
  #   
  # :named ::
  #   
  # :pac_string ::
  #   
  # 
  # @method _enum_proxy_type_t_
  # @return [Symbol]
  # @scope class
  enum :proxy_type_t, [
    :direct, 0,
    :named, 1,
    :pac_string, 2
  ]
  
  # ///
  # 
  # = Fields:
  # :proxy_type ::
  #   (Symbol from _enum_proxy_type_t_) 
  # :proxy_list ::
  #   (unknown) 
  class CefProxyInfoT < FFI::Struct
    layout :proxy_type, :proxy_type_t,
           :proxy_list, :char
  end
  
  # ///
  # 
  # <em>This entry is only for documentation and no real method. The FFI::Enum can be accessed via #enum_type(:dom_document_type_t).</em>
  # 
  # === Options:
  # :unknown ::
  #   
  # :html ::
  #   
  # :xhtml ::
  #   
  # :plugin ::
  #   
  # 
  # @method _enum_dom_document_type_t_
  # @return [Symbol]
  # @scope class
  enum :dom_document_type_t, [
    :unknown, 0,
    :html, 1,
    :xhtml, 2,
    :plugin, 3
  ]
  
  # ///
  # 
  # <em>This entry is only for documentation and no real method. The FFI::Enum can be accessed via #enum_type(:dom_event_category_t).</em>
  # 
  # === Options:
  # :unknown ::
  #   
  # :ui ::
  #   
  # :mouse ::
  #   
  # :mutation ::
  #   
  # :keyboard ::
  #   
  # :text ::
  #   
  # :composition ::
  #   
  # :drag ::
  #   
  # :clipboard ::
  #   
  # :message ::
  #   
  # :wheel ::
  #   
  # :before_text_inserted ::
  #   
  # :overflow ::
  #   
  # :page_transition ::
  #   
  # :popstate ::
  #   
  # :progress ::
  #   
  # :xmlhttprequest_progress ::
  #   
  # :webkit_animation ::
  #   
  # :webkit_transition ::
  #   
  # :before_load ::
  #   
  # 
  # @method _enum_dom_event_category_t_
  # @return [Symbol]
  # @scope class
  enum :dom_event_category_t, [
    :unknown, 0,
    :ui, 1,
    :mouse, 2,
    :mutation, 4,
    :keyboard, 8,
    :text, 16,
    :composition, 32,
    :drag, 64,
    :clipboard, 128,
    :message, 256,
    :wheel, 512,
    :before_text_inserted, 1024,
    :overflow, 2048,
    :page_transition, 4096,
    :popstate, 8192,
    :progress, 16384,
    :xmlhttprequest_progress, 32768,
    :webkit_animation, 65536,
    :webkit_transition, 131072,
    :before_load, 262144
  ]
  
  # ///
  # 
  # <em>This entry is only for documentation and no real method. The FFI::Enum can be accessed via #enum_type(:dom_event_phase_t).</em>
  # 
  # === Options:
  # :unknown ::
  #   
  # :capturing ::
  #   
  # :at_target ::
  #   
  # :bubbling ::
  #   
  # 
  # @method _enum_dom_event_phase_t_
  # @return [Symbol]
  # @scope class
  enum :dom_event_phase_t, [
    :unknown, 0,
    :capturing, 1,
    :at_target, 2,
    :bubbling, 3
  ]
  
  # ///
  # 
  # <em>This entry is only for documentation and no real method. The FFI::Enum can be accessed via #enum_type(:dom_node_type_t).</em>
  # 
  # === Options:
  # :unsupported ::
  #   
  # :element ::
  #   
  # :attribute ::
  #   
  # :text ::
  #   
  # :cdata_section ::
  #   
  # :entity_reference ::
  #   
  # :entity ::
  #   
  # :processing_instructions ::
  #   
  # :comment ::
  #   
  # :document ::
  #   
  # :document_type ::
  #   
  # :document_fragment ::
  #   
  # :notation ::
  #   
  # :xpath_namespace ::
  #   
  # 
  # @method _enum_dom_node_type_t_
  # @return [Symbol]
  # @scope class
  enum :dom_node_type_t, [
    :unsupported, 0,
    :element, 1,
    :attribute, 2,
    :text, 3,
    :cdata_section, 4,
    :entity_reference, 5,
    :entity, 6,
    :processing_instructions, 7,
    :comment, 8,
    :document, 9,
    :document_type, 10,
    :document_fragment, 11,
    :notation, 12,
    :xpath_namespace, 13
  ]
  
end
