# Generated by ffi-gen. Please do not change this file by hand.

require 'ffi'

module CEF
  extend FFI::Library
  ffi_lib 'cef'
  
  def self.attach_function(name, *_)
    begin; super; rescue FFI::NotFoundError => e
      (class << self; self; end).class_eval { define_method(name) { |*_| raise e } }
    end
  end
  
  # Set this object's values. If |copy| is true the source structure's values
  # will be copied instead of referenced.
  # 
  # = Fields:
  # :struct_type ::
  #   (unknown) 
  # :init ::
  #   (unknown) 
  class CefRectTraits < FFI::Struct
    layout :struct_type, :char,
           :init, :char
  end
  
  # Class representing a a keyboard event.
  # 
  # = Fields:
  # :struct_type ::
  #   (unknown) 
  # :init ::
  #   (unknown) 
  class CefPopupFeaturesTraits < FFI::Struct
    layout :struct_type, :char,
           :init, :char
  end
  
  # Class representing popup window features.
  # 
  # = Fields:
  # :struct_type ::
  #   (unknown) 
  # :init ::
  #   (unknown) 
  class CefSettingsTraits < FFI::Struct
    layout :struct_type, :char,
           :init, :char
  end
  
  # Class representing initialization settings.
  # 
  # = Fields:
  # :struct_type ::
  #   (unknown) 
  # :init ::
  #   (unknown) 
  class CefBrowserSettingsTraits < FFI::Struct
    layout :struct_type, :char,
           :init, :char
  end
  
  # Class representing browser initialization settings.
  # 
  # = Fields:
  # :struct_type ::
  #   (unknown) 
  # :init ::
  #   (unknown) 
  class CefURLPartsTraits < FFI::Struct
    layout :struct_type, :char,
           :init, :char
  end
  
  # Class representing a URL's component parts.
  # 
  # = Fields:
  # :struct_type ::
  #   (unknown) 
  # :init ::
  #   (unknown) 
  class CefTimeTraits < FFI::Struct
    layout :struct_type, :char,
           :init, :char
  end
  
  # means "not initialized".
  # 
  # = Fields:
  # :struct_type ::
  #   (unknown) 
  # :init ::
  #   (unknown) 
  class CefCookieTraits < FFI::Struct
    layout :struct_type, :char,
           :init, :char
  end
  
  # Class representing a cookie.
  # 
  # = Fields:
  # :struct_type ::
  #   (unknown) 
  # :init ::
  #   (unknown) 
  class CefProxyInfoTraits < FFI::Struct
    layout :struct_type, :char,
           :init, :char
  end
  
end
