# Generated by ffi-gen. Please do not change this file by hand.

require 'ffi'

module CEF
  extend FFI::Library
  ffi_lib 'cef'
  
  def self.attach_function(name, *_)
    begin; super; rescue FFI::NotFoundError => e
      (class << self; self; end).class_eval { define_method(name) { |*_| raise e } }
    end
  end
  
  # (Not documented)
  # 
  # = Fields:
  # :struct_type ::
  #   (unknown) 
  # :init ::
  #   (unknown) 
  class CefRectTraits < FFI::Struct
    layout :struct_type, :char,
           :init, :char
  end
  
  # ///
  # 
  # = Fields:
  # :struct_type ::
  #   (unknown) 
  # :init ::
  #   (unknown) 
  class CefPopupFeaturesTraits < FFI::Struct
    layout :struct_type, :char,
           :init, :char
  end
  
  # ///
  # 
  # = Fields:
  # :struct_type ::
  #   (unknown) 
  # :init ::
  #   (unknown) 
  class CefSettingsTraits < FFI::Struct
    layout :struct_type, :char,
           :init, :char
  end
  
  # ///
  # 
  # = Fields:
  # :struct_type ::
  #   (unknown) 
  # :init ::
  #   (unknown) 
  class CefBrowserSettingsTraits < FFI::Struct
    layout :struct_type, :char,
           :init, :char
  end
  
  # ///
  # 
  # = Fields:
  # :struct_type ::
  #   (unknown) 
  # :init ::
  #   (unknown) 
  class CefURLPartsTraits < FFI::Struct
    layout :struct_type, :char,
           :init, :char
  end
  
  # ///
  # 
  # = Fields:
  # :struct_type ::
  #   (unknown) 
  # :init ::
  #   (unknown) 
  class CefTimeTraits < FFI::Struct
    layout :struct_type, :char,
           :init, :char
  end
  
  # // means "not initialized".
  # 
  # = Fields:
  # :struct_type ::
  #   (unknown) 
  # :init ::
  #   (unknown) 
  class CefCookieTraits < FFI::Struct
    layout :struct_type, :char,
           :init, :char
  end
  
  # ///
  # 
  # = Fields:
  # :struct_type ::
  #   (unknown) 
  # :init ::
  #   (unknown) 
  class CefProxyInfoTraits < FFI::Struct
    layout :struct_type, :char,
           :init, :char
  end
  
end
