# Generated by ffi-gen. Please do not change this file by hand.

require 'ffi'

module CEF
  extend FFI::Library
  ffi_lib 'cef'
  
  def self.attach_function(name, *_)
    begin; super; rescue FFI::NotFoundError => e
      (class << self; self; end).class_eval { define_method(name) { |*_| raise e } }
    end
  end
  
  # Structure representing CefExecuteProcess arguments.
  # 
  # = Fields:
  # :argc ::
  #   (Integer) 
  # :argv ::
  #   (FFI::Pointer(**CharS)) 
  class MainArgsT < FFI::Struct
    layout :argc, :int,
           :argv, :pointer
  end
  
  # Class representing window information.
  # 
  # = Fields:
  # :parent_widget ::
  #   (FFI::Pointer(*Int)) 
  # :widget ::
  #   (FFI::Pointer(*Int)) 
  class WindowInfoT < FFI::Struct
    layout :parent_widget, :pointer,
           :widget, :pointer
  end
  
end
