# Generated by ffi-gen. Please do not change this file by hand.

require 'ffi'

module CEF
  extend FFI::Library
  ffi_lib 'cef'
  
  def self.attach_function(name, *_)
    begin; super; rescue FFI::NotFoundError => e
      (class << self; self; end).class_eval { define_method(name) { |*_| raise e } }
    end
  end
  
  # (Not documented)
  class CefBrowserT < FFI::Struct
    layout :dummy, :char
  end
  
  # (Not documented)
  class CefBrowserT < FFI::Struct
    layout :dummy, :char
  end
  
  # (Not documented)
  class CefFrameT < FFI::Struct
    layout :dummy, :char
  end
  
  # (Not documented)
  class CefBrowserT < FFI::Struct
    layout :dummy, :char
  end
  
  # (Not documented)
  class CefBrowserT < FFI::Struct
    layout :dummy, :char
  end
  
  # (Not documented)
  class CefBrowserT < FFI::Struct
    layout :dummy, :char
  end
  
  # (Not documented)
  class CefBrowserT < FFI::Struct
    layout :dummy, :char
  end
  
  # (Not documented)
  # 
  # = Fields:
  # :base ::
  #   (unknown) ///
  # :on_loading_state_change ::
  #   (FFI::Pointer(*)) ///
  # :on_address_change ::
  #   (FFI::Pointer(*)) ///
  # :on_title_change ::
  #   (FFI::Pointer(*)) ///
  # :on_tooltip ::
  #   (FFI::Pointer(*)) ///
  # :on_status_message ::
  #   (FFI::Pointer(*)) ///
  # :on_console_message ::
  #   (FFI::Pointer(*)) ///
  class CefDisplayHandlerT < FFI::Struct
    layout :base, :char,
           :on_loading_state_change, :pointer,
           :on_address_change, :pointer,
           :on_title_change, :pointer,
           :on_tooltip, :pointer,
           :on_status_message, :pointer,
           :on_console_message, :pointer
  end
  
end
