# Generated by ffi-gen. Please do not change this file by hand.

require 'ffi'

module CEF
  extend FFI::Library
  ffi_lib 'cef'
  
  def self.attach_function(name, *_)
    begin; super; rescue FFI::NotFoundError => e
      (class << self; self; end).class_eval { define_method(name) { |*_| raise e } }
    end
  end
  
  # (Not documented)
  class CefBrowserT < FFI::Struct
    layout :dummy, :char
  end
  
  # (Not documented)
  class CefBrowserT < FFI::Struct
    layout :dummy, :char
  end
  
  # (Not documented)
  # 
  # = Fields:
  # :base ::
  #   (unknown) ///
  # :on_pre_key_event ::
  #   (FFI::Pointer(*)) // shortcut set |is_keyboard_shortcut| to true (1) and return false (0).
  # :on_key_event ::
  #   (FFI::Pointer(*)) ///
  class CefKeyboardHandlerT < FFI::Struct
    layout :base, :char,
           :on_pre_key_event, :pointer,
           :on_key_event, :pointer
  end
  
end
