# Generated by ffi-gen. Please do not change this file by hand.

require 'ffi'

module CEF
  extend FFI::Library
  ffi_lib 'cef'
  
  def self.attach_function(name, *_)
    begin; super; rescue FFI::NotFoundError => e
      (class << self; self; end).class_eval { define_method(name) { |*_| raise e } }
    end
  end
  
  # (Not documented)
  class CefRequestT < FFI::Struct
    layout :dummy, :char
  end
  
  # (Not documented)
  class CefCallbackT < FFI::Struct
    layout :dummy, :char
  end
  
  # (Not documented)
  class CefResponseT < FFI::Struct
    layout :dummy, :char
  end
  
  # (Not documented)
  class CefCallbackT < FFI::Struct
    layout :dummy, :char
  end
  
  # (Not documented)
  # 
  # = Fields:
  # :base ::
  #   (unknown) ///
  # :process_request ::
  #   (FFI::Pointer(*)) ///
  # :get_response_headers ::
  #   (FFI::Pointer(*)) ///
  # :read_response ::
  #   (FFI::Pointer(*)) ///
  # :can_get_cookie ::
  #   (FFI::Pointer(*)) ///
  # :can_set_cookie ::
  #   (FFI::Pointer(*)) ///
  # :cancel ::
  #   (FFI::Pointer(*)) ///
  class CefResourceHandlerT < FFI::Struct
    layout :base, :char,
           :process_request, :pointer,
           :get_response_headers, :pointer,
           :read_response, :pointer,
           :can_get_cookie, :pointer,
           :can_set_cookie, :pointer,
           :cancel, :pointer
  end
  
end
