# Generated by ffi-gen. Please do not change this file by hand.

require 'ffi'

module CEF
  extend FFI::Library
  ffi_lib 'cef'
  
  def self.attach_function(name, *_)
    begin; super; rescue FFI::NotFoundError => e
      (class << self; self; end).class_eval { define_method(name) { |*_| raise e } }
    end
  end
  
  # (Not documented)
  # 
  # = Fields:
  # :base ::
  #   (unknown) ///
  # :cont ::
  #   (FFI::Pointer(*)) ///
  class CefGeolocationCallbackT < FFI::Struct
    layout :base, :char,
           :cont, :pointer
  end
  
  # (Not documented)
  class CefBrowserT < FFI::Struct
    layout :dummy, :char
  end
  
  # (Not documented)
  class CefBrowserT < FFI::Struct
    layout :dummy, :char
  end
  
  # ///
  # 
  # = Fields:
  # :base ::
  #   (unknown) ///
  # :on_request_geolocation_permission ::
  #   (FFI::Pointer(*)) ///
  # :on_cancel_geolocation_permission ::
  #   (FFI::Pointer(*)) ///
  class CefGeolocationHandlerT < FFI::Struct
    layout :base, :char,
           :on_request_geolocation_permission, :pointer,
           :on_cancel_geolocation_permission, :pointer
  end
  
end
