# Generated by ffi-gen. Please do not change this file by hand.

require 'ffi'

module CEF
  extend FFI::Library
  ffi_lib 'cef'
  
  def self.attach_function(name, *_)
    begin; super; rescue FFI::NotFoundError => e
      (class << self; self; end).class_eval { define_method(name) { |*_| raise e } }
    end
  end
  
  # (Not documented)
  class CefBrowserT < FFI::Struct
    layout :dummy, :char
  end
  
  # (Not documented)
  class CefClientT < FFI::Struct
    layout :dummy, :char
  end
  
  # (Not documented)
  class CefBrowserT < FFI::Struct
    layout :dummy, :char
  end
  
  # (Not documented)
  class CefBrowserT < FFI::Struct
    layout :dummy, :char
  end
  
  # (Not documented)
  class CefBrowserT < FFI::Struct
    layout :dummy, :char
  end
  
  # (Not documented)
  class CefBrowserT < FFI::Struct
    layout :dummy, :char
  end
  
  # (Not documented)
  # 
  # = Fields:
  # :base ::
  #   (unknown) ///
  # :on_before_popup ::
  #   (FFI::Pointer(*)) ///
  # :on_after_created ::
  #   (FFI::Pointer(*)) ///
  # :run_modal ::
  #   (FFI::Pointer(*)) ///
  # :do_close ::
  #   (FFI::Pointer(*)) ///
  # :on_before_close ::
  #   (FFI::Pointer(*)) ///
  class CefLifeSpanHandlerT < FFI::Struct
    layout :base, :char,
           :on_before_popup, :pointer,
           :on_after_created, :pointer,
           :run_modal, :pointer,
           :do_close, :pointer,
           :on_before_close, :pointer
  end
  
end
