# Generated by ffi-gen. Please do not change this file by hand.

require 'ffi'

module CEF
  extend FFI::Library
  ffi_lib 'cef'
  
  def self.attach_function(name, *_)
    begin; super; rescue FFI::NotFoundError => e
      (class << self; self; end).class_eval { define_method(name) { |*_| raise e } }
    end
  end
  
  # (Not documented)
  class CefAppT < FFI::Struct
    layout :dummy, :char
  end
  
  # (Not documented)
  # 
  # @method execute_process(args, application)
  # @param [FFI::Pointer(*CefMainArgsT)] args 
  # @param [CefAppT] application 
  # @return [Integer] 
  # @scope class
  attach_function :execute_process, :cef_execute_process, [:pointer, CefAppT], :int
  
  # ///
  class CefAppT < FFI::Struct
    layout :dummy, :char
  end
  
  # (Not documented)
  # 
  # @method initialize(args, settings, application)
  # @param [FFI::Pointer(*CefMainArgsT)] args 
  # @param [FFI::Pointer(*CefSettingsT)] settings 
  # @param [CefAppT] application 
  # @return [Integer] 
  # @scope class
  attach_function :initialize, :cef_initialize, [:pointer, :pointer, CefAppT], :int
  
  # (Not documented)
  # 
  # @method shutdown()
  # @return [nil] 
  # @scope class
  attach_function :shutdown, :cef_shutdown, [], :void
  
  # (Not documented)
  # 
  # @method do_message_loop_work()
  # @return [nil] 
  # @scope class
  attach_function :do_message_loop_work, :cef_do_message_loop_work, [], :void
  
  # (Not documented)
  # 
  # @method run_message_loop()
  # @return [nil] 
  # @scope class
  attach_function :run_message_loop, :cef_run_message_loop, [], :void
  
  # (Not documented)
  # 
  # @method quit_message_loop()
  # @return [nil] 
  # @scope class
  attach_function :quit_message_loop, :cef_quit_message_loop, [], :void
  
  # (Not documented)
  class CefCommandLineT < FFI::Struct
    layout :dummy, :char
  end
  
  # (Not documented)
  class CefSchemeRegistrarT < FFI::Struct
    layout :dummy, :char
  end
  
  # (Not documented)
  class CefResourceBundleHandlerT < FFI::Struct
    layout :dummy, :char
  end
  
  # (Not documented)
  class CefBrowserProcessHandlerT < FFI::Struct
    layout :dummy, :char
  end
  
  # (Not documented)
  class CefRenderProcessHandlerT < FFI::Struct
    layout :dummy, :char
  end
  
  # ///
  # 
  # = Fields:
  # :base ::
  #   (unknown) ///
  # :on_before_command_line_processing ::
  #   (FFI::Pointer(*)) ///
  # :on_register_custom_schemes ::
  #   (FFI::Pointer(*)) ///
  # :get_resource_bundle_handler ::
  #   (FFI::Pointer(*)) ///
  # :get_browser_process_handler ::
  #   (FFI::Pointer(*)) ///
  # :get_render_process_handler ::
  #   (FFI::Pointer(*)) ///
  class CefAppT < FFI::Struct
    layout :base, :char,
           :on_before_command_line_processing, :pointer,
           :on_register_custom_schemes, :pointer,
           :get_resource_bundle_handler, :pointer,
           :get_browser_process_handler, :pointer,
           :get_render_process_handler, :pointer
  end
  
end
