# Generated by ffi-gen. Please do not change this file by hand.

require 'ffi'

module CEF
  extend FFI::Library
  ffi_lib 'cef'
  
  def self.attach_function(name, *_)
    begin; super; rescue FFI::NotFoundError => e
      (class << self; self; end).class_eval { define_method(name) { |*_| raise e } }
    end
  end
  
  # (Not documented)
  # 
  # @method parse_url(url, parts)
  # @param [FFI::Pointer(*StringT)] url 
  # @param [FFI::Pointer(*CefUrlpartsT)] parts 
  # @return [Integer] 
  # @scope class
  attach_function :parse_url, :cef_parse_url, [:pointer, :pointer], :int
  
  # (Not documented)
  # 
  # @method create_url(parts, url)
  # @param [FFI::Pointer(*CefUrlpartsT)] parts 
  # @param [FFI::Pointer(*StringT)] url 
  # @return [Integer] 
  # @scope class
  attach_function :create_url, :cef_create_url, [:pointer, :pointer], :int
  
end
