# Generated by ffi-gen. Please do not change this file by hand.

require 'ffi'

module CEF
  extend FFI::Library
  ffi_lib 'cef'
  
  def self.attach_function(name, *_)
    begin; super; rescue FFI::NotFoundError => e
      (class << self; self; end).class_eval { define_method(name) { |*_| raise e } }
    end
  end
  
  # Structure defining the reference count implementation functions. All
  # framework structures must include the cef_base_t structure first.
  # 
  # = Fields:
  # :size ::
  #   (Integer) Size of the data structure.
  # :add_ref ::
  #   (FFI::Pointer(*)) Increment the reference count.
  # :release ::
  #   (FFI::Pointer(*)) Decrement the reference count.  Delete this object when no references
  #   remain.
  # :get_refct ::
  #   (FFI::Pointer(*)) Returns the current number of references.
  class Base < FFI::Struct
    layout :size, :ulong,
           :add_ref, :pointer,
           :release, :pointer,
           :get_refct, :pointer
  end
  
end
