# Generated by ffi-gen. Please do not change this file by hand.

require 'ffi'

module CEF
  extend FFI::Library
  ffi_lib 'cef'
  
  def self.attach_function(name, *_)
    begin; super; rescue FFI::NotFoundError => e
      (class << self; self; end).class_eval { define_method(name) { |*_| raise e } }
    end
  end
  
  # (Not documented)
  class CefListValueT < FFI::Struct
    layout :dummy, :char
  end
  
  # (Not documented)
  # 
  # = Fields:
  # :base ::
  #   (unknown) ///
  # :is_valid ::
  #   (FFI::Pointer(*)) ///
  # :is_read_only ::
  #   (FFI::Pointer(*)) ///
  # :copy ::
  #   (FFI::Pointer(*)) ///
  # :get_name ::
  #   (FFI::Pointer(*)) // The resulting string must be freed by calling cef_string_userfree_free().
  # :get_argument_list ::
  #   (FFI::Pointer(*)) ///
  class CefProcessMessageT < FFI::Struct
    layout :base, :char,
           :is_valid, :pointer,
           :is_read_only, :pointer,
           :copy, :pointer,
           :get_name, :pointer,
           :get_argument_list, :pointer
  end
  
  # (Not documented)
  # 
  # @method process_message_create(name)
  # @param [FFI::Pointer(*StringT)] name 
  # @return [CefProcessMessageT] 
  # @scope class
  attach_function :process_message_create, :cef_process_message_create, [:pointer], CefProcessMessageT
  
end
