# Generated by ffi-gen. Please do not change this file by hand.

require 'ffi'

module CEF
  extend FFI::Library
  ffi_lib 'cef'
  
  def self.attach_function(name, *_)
    begin; super; rescue FFI::NotFoundError => e
      (class << self; self; end).class_eval { define_method(name) { |*_| raise e } }
    end
  end
  
  # Structure that supports the reading of XML data via the libxml streaming API.
  # The functions of this structure should only be called on the thread that
  # creates the object.
  # 
  # = Fields:
  # :base ::
  #   (unknown) Base structure.
  # :move_to_next_node ::
  #   (FFI::Pointer(*)) Moves the cursor to the next node in the document. This function must be
  #   called at least once to set the current cursor position. Returns true (1)
  #   if the cursor position was set successfully.
  # :close ::
  #   (FFI::Pointer(*)) Close the document. This should be called directly to ensure that cleanup
  #   occurs on the correct thread.
  # :has_error ::
  #   (FFI::Pointer(*)) Returns true (1) if an error has been reported by the XML parser.
  # :get_error ::
  #   (FFI::Pointer(*)) The resulting string must be freed by calling cef_string_userfree_free().
  # :get_type ::
  #   (FFI::Pointer(*)) Returns the node type.
  # :get_depth ::
  #   (FFI::Pointer(*)) Returns the node depth. Depth starts at 0 for the root node.
  # :get_local_name ::
  #   (FFI::Pointer(*)) The resulting string must be freed by calling cef_string_userfree_free().
  # :get_prefix ::
  #   (FFI::Pointer(*)) The resulting string must be freed by calling cef_string_userfree_free().
  # :get_qualified_name ::
  #   (FFI::Pointer(*)) The resulting string must be freed by calling cef_string_userfree_free().
  # :get_namespace_uri ::
  #   (FFI::Pointer(*)) The resulting string must be freed by calling cef_string_userfree_free().
  # :get_base_uri ::
  #   (FFI::Pointer(*)) The resulting string must be freed by calling cef_string_userfree_free().
  # :get_xml_lang ::
  #   (FFI::Pointer(*)) The resulting string must be freed by calling cef_string_userfree_free().
  # :is_empty_element ::
  #   (FFI::Pointer(*)) Returns true (1) if the node represents an NULL element. <a/> is considered
  #   NULL but <a></a> is not.
  # :has_value ::
  #   (FFI::Pointer(*)) Returns true (1) if the node has a text value.
  # :get_value ::
  #   (FFI::Pointer(*)) The resulting string must be freed by calling cef_string_userfree_free().
  # :has_attributes ::
  #   (FFI::Pointer(*)) Returns true (1) if the node has attributes.
  # :get_attribute_count ::
  #   (FFI::Pointer(*)) Returns the number of attributes.
  # :get_attribute_byindex ::
  #   (FFI::Pointer(*)) The resulting string must be freed by calling cef_string_userfree_free().
  # :get_attribute_byqname ::
  #   (FFI::Pointer(*)) The resulting string must be freed by calling cef_string_userfree_free().
  # :get_attribute_bylname ::
  #   (FFI::Pointer(*)) The resulting string must be freed by calling cef_string_userfree_free().
  # :get_inner_xml ::
  #   (FFI::Pointer(*)) The resulting string must be freed by calling cef_string_userfree_free().
  # :get_outer_xml ::
  #   (FFI::Pointer(*)) The resulting string must be freed by calling cef_string_userfree_free().
  # :get_line_number ::
  #   (FFI::Pointer(*)) Returns the line number for the current node.
  # :move_to_attribute_byindex ::
  #   (FFI::Pointer(*)) Moves the cursor to the attribute at the specified 0-based index. Returns
  #   true (1) if the cursor position was set successfully.
  # :move_to_attribute_byqname ::
  #   (FFI::Pointer(*)) Moves the cursor to the attribute with the specified qualified name.
  #   Returns true (1) if the cursor position was set successfully.
  # :move_to_attribute_bylname ::
  #   (FFI::Pointer(*)) Moves the cursor to the attribute with the specified local name and
  #   namespace URI. Returns true (1) if the cursor position was set
  #   successfully.
  # :move_to_first_attribute ::
  #   (FFI::Pointer(*)) Moves the cursor to the first attribute in the current element. Returns
  #   true (1) if the cursor position was set successfully.
  # :move_to_next_attribute ::
  #   (FFI::Pointer(*)) Moves the cursor to the next attribute in the current element. Returns true
  #   (1) if the cursor position was set successfully.
  # :move_to_carrying_element ::
  #   (FFI::Pointer(*)) Moves the cursor back to the carrying element. Returns true (1) if the
  #   cursor position was set successfully.
  class CefXmlReaderT < FFI::Struct
    layout :base, :char,
           :move_to_next_node, :pointer,
           :close, :pointer,
           :has_error, :pointer,
           :get_error, :pointer,
           :get_type, :pointer,
           :get_depth, :pointer,
           :get_local_name, :pointer,
           :get_prefix, :pointer,
           :get_qualified_name, :pointer,
           :get_namespace_uri, :pointer,
           :get_base_uri, :pointer,
           :get_xml_lang, :pointer,
           :is_empty_element, :pointer,
           :has_value, :pointer,
           :get_value, :pointer,
           :has_attributes, :pointer,
           :get_attribute_count, :pointer,
           :get_attribute_byindex, :pointer,
           :get_attribute_byqname, :pointer,
           :get_attribute_bylname, :pointer,
           :get_inner_xml, :pointer,
           :get_outer_xml, :pointer,
           :get_line_number, :pointer,
           :move_to_attribute_byindex, :pointer,
           :move_to_attribute_byqname, :pointer,
           :move_to_attribute_bylname, :pointer,
           :move_to_first_attribute, :pointer,
           :move_to_next_attribute, :pointer,
           :move_to_carrying_element, :pointer
  end
  
  # (Not documented)
  class CefStreamReaderT < FFI::Struct
    layout :dummy, :char
  end
  
  # Create a new cef_xml_reader_t object. The returned object's functions can
  # only be called from the thread that created the object.
  # 
  # @method xml_reader_create(stream, encoding_type, uri)
  # @param [CefStreamReaderT] stream 
  # @param [unknown] encoding_type 
  # @param [FFI::Pointer(*StringT)] uri 
  # @return [CefXmlReaderT] 
  # @scope class
  attach_function :xml_reader_create, :cef_xml_reader_create, [CefStreamReaderT, :char, :pointer], CefXmlReaderT
  
end
