# Generated by ffi-gen. Please do not change this file by hand.

require 'ffi'

module CEF
  extend FFI::Library
  ffi_lib 'cef'
  
  def self.attach_function(name, *_)
    begin; super; rescue FFI::NotFoundError => e
      (class << self; self; end).class_eval { define_method(name) { |*_| raise e } }
    end
  end
  
  # Structure used to implement a custom resource bundle structure. The functions
  # of this structure may be called on multiple threads.
  # 
  # = Fields:
  # :base ::
  #   (unknown) Base structure.
  # :get_localized_string ::
  #   (FFI::Pointer(*)) Called to retrieve a localized translation for the string specified by
  #   |message_id|. To provide the translation set |string| to the translation
  #   string and return true (1). To use the default translation return false
  #   (0). Supported message IDs are listed in cef_pack_strings.h.
  # :get_data_resource ::
  #   (FFI::Pointer(*)) Called to retrieve data for the resource specified by |resource_id|. To
  #   provide the resource data set |data| and |data_size| to the data pointer
  #   and size respectively and return true (1). To use the default resource data
  #   return false (0). The resource data will not be copied and must remain
  #   resident in memory. Supported resource IDs are listed in
  #   cef_pack_resources.h.
  class ResourceBundleHandlerT < FFI::Struct
    layout :base, :char,
           :get_localized_string, :pointer,
           :get_data_resource, :pointer
  end
  
end
